### ISSUE TITLE
Fails to build with python3.11

### ISSUE THREAD

**Issue by boydkelly** [amueller/word_cloud#691]
#### Description
wordcloud fails to build with python 3.11

#### Steps/Code to Reproduce
````
 python --version
Python 3.11.0rc2

pip install wordcloud

----
clipped
----

      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.11 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-cpython-311/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud
````

#### Expected Results
successful build

#### Actual Results
Fails as ber above

**Comment by amueller** [comment]
Thanks. I assume it'll require running cython again, the C file is probably ancient by now. Also we need to add more recent python versions to the CI and build matrix. Ideally you wouldn't compile locally.
Are you interested in working on this issue?

**Comment by darkaico** [comment]
Hi @amueller and @boydkelly 
I just upload a PR that should fix this issue: https://github.com/amueller/word_cloud/pull/697

**Comment by Barry1** [comment]
I stumpled on the same issue with final `python3.11` and `wordcloud 1.8.2.2`.
The first problem could be solved by setting `export CPATH=~/.pyenv/versions/3.11.0/include/python3.11/cpython` but after wards it crashed again

```
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [271 lines of output]
        running bdist_wheel
        running build
        running build_py
        creating build
        creating build/lib.linux-x86_64-cpython-311
        creating build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/_version.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/__init__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/tokenization.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/__main__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/stopwords -> build/lib.linux-x86_64-cpython-311/wordcloud
        copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-cpython-311/wordcloud
        UPDATING build/lib.linux-x86_64-cpython-311/wordcloud/_version.py
        set build/lib.linux-x86_64-cpython-311/wordcloud/_version.py to '1.8.2.2'
        running build_ext
        building 'wordcloud.query_integral_image' extension
        creating build/temp.linux-x86_64-cpython-311
        creating build/temp.linux-x86_64-cpython-311/wordcloud
        gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/ebeling/GitHub/TSH/WordCloud/.venv/include -I~/.pyenv/versions/3.11.0/include/python3.11 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-cpython-311/wordcloud/query_integral_image.o
        wordcloud/query_integral_image.c: In function ‘__Pyx_InitCachedConstants’:
        wordcloud/query_integral_image.c:16618:272: warning: passing argument 14 of ‘PyCode_New’ makes pointer from integer without a cast [-Wint-conversion]
        16618 |   __pyx_codeobj__20 = (PyObject*)__Pyx_PyCode_New(4, 0, 11, 0, CO_OPTIMIZED|CO_NEWLOCALS, __pyx_empty_bytes, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_tuple__19, __pyx_empty_tuple, __pyx_empty_tuple, __pyx_kp_s_query_integral_image_pyx, __pyx_n_s_q:

```
