### ISSUE TITLE
wordcloud not working in 3.8

### ISSUE THREAD

**Issue by btsfav** [amueller/word_cloud#630]
Version: wordcloud-1.8.1, python3.8 
OS: Linux Mint
IDE: pycharm

> from wordcloud import WordCloud

`Traceback (most recent call last):
  File "/home/ho/PycharmProjects/test/wordcloud.py", line 6, in <module>
    from wordcloud import WordCloud
  File "/home/ho/PycharmProjects/test/wordcloud.py", line 6, in <module>
    from wordcloud import WordCloud
ImportError: cannot import name 'WordCloud' from partially initialized module 'wordcloud' (most likely due to a circular import) (/home/ho/PycharmProjects/test/wordcloud.py)`

**Comment by amueller** [comment]
I think this is because you named your file wordcloud, so it tries to import itself.

**Comment by btsfav** [comment]
Unfortunately that was not the problem

> Cannot find reference 'WordCloud' in 'wordcloud.py | __init__.py'

**Comment by btsfav** [comment]
oops, didn't mean to close it :)

**Comment by amueller** [comment]
Can you please provide the full traceback?

**Comment by btsfav** [comment]
```
/home/ho/PycharmProjects/test/venv/bin/python /home/ho/PycharmProjects/test/wc.py
Traceback (most recent call last):
  File "/home/ho/PycharmProjects/test/wc.py", line 5, in <module>
    from wordcloud import WordCloud
  File "/home/ho/PycharmProjects/test/wordcloud.py", line 6, in <module>
    from wordcloud import WordCloud
ImportError: cannot import name 'WordCloud' from partially initialized module 'wordcloud' (most likely due to a circular import) (/home/ho/PycharmProjects/test/wordcloud.py)

Process finished with exit code 1
```

**Comment by amueller** [comment]
So is `test/wordcloud.py` your file or the wordcloud module?
