### ISSUE TITLE
fatal error on Fedora37: longintrepr.h: No such file or directory

### ISSUE THREAD

**Issue by trblnyx** [amueller/word_cloud#708]
#### Description

Can't install wordcloud on Fedora37: legacy-install AND wheel-install failed with missing include file "longintrepr.h"
BTW it worked with Fedora36

#### Steps/Code to Reproduce

$ pip install wordcloud 

#### Expected Results

wordcloud installed

#### Actual Results
Defaulting to user installation because normal site-packages is not writeable
Collecting wordcloud
  Using cached wordcloud-1.8.2.2.tar.gz (220 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.6.1 in /usr/lib64/python3.11/site-packages (from wordcloud) (1.22.0)
Requirement already satisfied: pillow in /usr/lib64/python3.11/site-packages (from wordcloud) (9.2.0)
Requirement already satisfied: matplotlib in /usr/lib64/python3.11/site-packages (from wordcloud) (3.6.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/lib64/python3.11/site-packages (from matplotlib->wordcloud) (1.0.6)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.11/site-packages (from matplotlib->wordcloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/lib64/python3.11/site-packages (from matplotlib->wordcloud) (4.37.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/lib64/python3.11/site-packages (from matplotlib->wordcloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3.11/site-packages (from matplotlib->wordcloud) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in /usr/lib/python3.11/site-packages (from matplotlib->wordcloud) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3.11/site-packages (from matplotlib->wordcloud) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.16.0)
Building wheels for collected packages: wordcloud
  Building wheel for wordcloud (setup.py): started
  Building wheel for wordcloud (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/tokenization.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/_version.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/__main__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/__init__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/stopwords -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-cpython-311/wordcloud
      UPDATING build/lib.linux-x86_64-cpython-311/wordcloud/_version.py
      set build/lib.linux-x86_64-cpython-311/wordcloud/_version.py to '1.8.2.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/wordcloud
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.11 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-cpython-311/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for wordcloud
  Running setup.py clean for wordcloud
Failed to build wordcloud
Installing collected packages: wordcloud
  Running setup.py install for wordcloud: started
  Running setup.py install for wordcloud: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for wordcloud did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running install
      /usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-311
      creating build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/wordcloud_cli.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/wordcloud.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/tokenization.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/color_from_image.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/_version.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/__main__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/__init__.py -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/stopwords -> build/lib.linux-x86_64-cpython-311/wordcloud
      copying wordcloud/DroidSansMono.ttf -> build/lib.linux-x86_64-cpython-311/wordcloud
      UPDATING build/lib.linux-x86_64-cpython-311/wordcloud/_version.py
      set build/lib.linux-x86_64-cpython-311/wordcloud/_version.py to '1.8.2.2'
      running build_ext
      building 'wordcloud.query_integral_image' extension
      creating build/temp.linux-x86_64-cpython-311
      creating build/temp.linux-x86_64-cpython-311/wordcloud
      gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python3.11 -c wordcloud/query_integral_image.c -o build/temp.linux-x86_64-cpython-311/wordcloud/query_integral_image.o
      wordcloud/query_integral_image.c:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> wordcloud

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

#### Versions

Linux-6.0.15-300.fc37.x86_64-x86_64-with-glibc2.36
Python 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
NumPy 1.22.0
matplotlib 3.6.2
Traceback (most recent call last):
  File "/home/arp/foo.py", line 5, in <module>
    import wordcloud; print("wordcoud", wordcloud.__version__)
    ^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'wordcloud'

**Comment by jadelrio** [comment]
I have the same problem. I cannot install the information is the same.

**Comment by dlukes** [comment]
I think this is fixed in master (https://github.com/amueller/word_cloud/pull/697), it just hasn't made it into a release yet.

**Comment by Valinquish** [comment]
`wordcloud` does work on Python 3.11. For anyone struggling to install `wordcloud` on Python 3.11:
- Clone this repository `git clone ...`
- Run `pip` install on this repository : `python -m pip install -e full/path/to/the/cloned/repository`

This should also works: 
`python -m pip install git+https://github.com/amueller/word_cloud#egg=wordcloud`

As per the `README`, it requires a C compiler set up.

**Comment by trblnyx** [comment]
Thanks. Best regards.

**Comment by amueller** [comment]
There should be a 3.11 binary released now, and you should be able to pip install using just "pip install wordcloud"

**Comment by amueller** [comment]
Closing, let me know if there's still an issue!
